### ISSUE TITLE
No way to remove a website from keep-awake.herokuapp

### ISSUE THREAD

**Issue by rrshaban** [rpearce/keep_awake#1]
I've added a site but have since decided I would like to remove it; how can I do this?

**Comment by artemave** [comment]
+1

**Comment by DanielaSfregola** [comment]
+1

**Comment by matiasfha** [comment]
+1

**Comment by muescha** [comment]
+1
most of the herokuapp websites on the keepawake website are not exisits anymore

**Comment by muescha** [comment]
and for the new 18/7 policy for free dyno with 6h sleep requirement it is not helpful

**Comment by rrshaban** [comment]
@rpearce, thoughts?

**Comment by rpearce** [comment]
@rrshaban I wasn't getting these notifications, and I am sorry for not responding.

Given this is no longer a viable option for Heroku, I am considering taking the service down. Do you have a problem with this?

**Comment by rpearce** [comment]
This was a one-day project 2 years ago that I believe has run its course of usefulness.

**Comment by rrshaban** [comment]
Doesn't seem there would be any harm killing the app; might decrease confusion

**Comment by rpearce** [comment]
I've killed the application. I apologize for any trouble this caused you all.
